### ISSUE TITLE
allow instructing the (multiple) content-type(s) to be retrieved

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/py-trav-harv#31]
we recently discovered that e.g. orcid produces quite different representations (amount of included triples) based on what conneg instruction one provides

compare:
```bash
$ curl -L --url "https://orcid.org/0000-0003-4305-0617" -H "Accept: text/turtle" 
$ curl -L --url "https://orcid.org/0000-0003-4305-0617" -H "Accept: application/ld+json" 
```

given this fact, it would be nice to be able to include in the task/executor, which actual content-formats it should be harvesting

e.g. for orcid access, one might want to request both json-ld and triple to maximalise the retrieved content

**Comment by cedricdcc** [comment]
Closed by merge of #52
