### ISSUE TITLE
provide proper isolation of failures during path assurtion

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/py-trav-harv#37]
![image](https://github.com/vliz-be-opsci/py-trav-harv/assets/64254968/f9ba83fa-0131-444f-86ce-8f7d76074a78)

in the above screenshot one can see that inserting a faulty triple in the database ([known issue](https://github.com/vliz-be-opsci/py-RDF-store/issues/46)) brings the whole system down, instead travharv should continue with asserting the next, continuing with the next subject, continuing to execute other tasks

this should be handled through proper try/catch + logging

**Comment by cedricdcc** [comment]
https://github.com/vliz-be-opsci/py-trav-harv/commit/85faca30321cd1b865b63a90f5d18321799916f7
