### ISSUE TITLE
use new feature to cleanup graphs

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/py-trav-harv#40]
as it becomes available in rdf-store -- see https://github.com/vliz-be-opsci/py-RDF-store/issues/46

**Comment by marc-portier** [comment]
toto --> think about introducing a config entry to contain specific clean-specs on task level

**Comment by marc-portier** [comment]
for now we can probably just rely on the default cleaning (all available features)
so either just close, or push up to 004 to allow for custom / extra cleaning in the travharv operation

**Comment by cedricdcc** [comment]
Since the default cleaning of the py-rdf-store is being used and no other remnants of a cleaner in travharv are found this issue will be closed.
